### ISSUE TITLE
Sandbox TLS 1.2 support and Apache HttpClient/HttpCore best practices?

### ISSUE THREAD

**Issue by richardrega** [AuthorizeNet/sdk-java#114]
This SDK currently uses "DefaultHttpClient()" to make HTTP requests.  As an experiment I upgraded the httpclient-4.0.1 and httpcore-4.0.1 JARs  and added some functions to build a custom SSLContext into the HttpClient executed by the SDK API calls.

Does this SDK expect us to configure our servers to only make TLS 1.2 HTTPS requests?
Options like "-Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2" or "SSLProtocol -all +TLSv1.2"

Is there a newer version of the SDK coming that has the upgraded HttpClient libraries built in for us?
Is there some way to insert a custom HttpClient into the
`		CreateTransactionController controller = new CreateTransactionController(apiRequest);
		controller.execute();
		CreateTransactionResponse response = controller.getApiResponse();`
or
`response = merchant.postTransaction(transaction);`
process?

So far, I've only been able to place new sandbox transactions with my modified SDK, changing my web and application server options has not worked yet.

**Comment by richardrega** [comment]
Too see what I'm talking about:
https://github.com/richardrega/sdk-java/commit/c63c95e94e1971677b5c8940962056060c237e06

**Comment by ammmze** [comment]
I'm struggling with the same thing ... running on java 7 with those `JAVA_OPTS`, I still cannot connect. So far I've only been able to connect using java 8 (though I think I still had those `JAVA_OPTS` set when I tried java 8), but that is a larger risk that we are not ready for yet.

**Comment by NexWeb** [comment]
```
try {
        SSLContext ctx = SSLContext.getInstance("TLSv1.2");
        ctx.init(null, null, null);
        SSLContext.setDefault(ctx);
} catch (Exception e) {
        System.out.println(e.getMessage());
}
```

**Comment by ammmze** [comment]
Okay...so I was able to get it working by forcing http client back to the original 4.0.1. We have a dependency that was pulling a newer v4.5.3 httpclient which is why the `-Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2` properties weren't working for me. But i'm not sure what is gonna break by dropping us back down to this older httpclient.

**Comment by ammmze** [comment]
Thanks @NexWeb! Looks like that works as an alternative to the system properties. Unfortunately, looks like it still requires me to force pulling in the older http client (the one specified by the auth.net sdk).

**Comment by NexWeb** [comment]
Another way:

 ```
    final SSLContext ctx = SSLContext.getInstance("TLSv1.2");
			ctx.init(null,null, new java.security.SecureRandom());
			final SSLSocketFactory socketFactory = ctx.getSocketFactory();
			HttpsURLConnection.setDefaultSSLSocketFactory(socketFactory);
```

**Comment by ammmze** [comment]
Thanks @NexWeb! I had tried using `HttpsURLConnection.setDefaultSSLSocketFactory(...)` but results were the same. We're in the process of getting buy off to just do the java 8 upgrade (we've been wanting to, this will just be the kicker to do it) which resolves the issue.

**Comment by NexWeb** [comment]
That should solve it.

**Comment by gserbousek** [comment]
I'm having the exact same issue as ammmze.  Unfortunately I can't move back to version 4.0.1 of the httpClient and also can't move to Java 8 at this time.  After trying your two suggestions and setting the JAVA opts to -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2  the java network debug log is still showing an attempt to connect via TLS1v1.  Any other ideas on how to force the sdk to use a TLSv1.2 connection?

**Comment by richardrega** [comment]
I'm in the same situation.  Stuck with Java 7, and the JAVA_OPTS aren't working for our system configuration.  The latest version of my solution so far is here https://github.com/richardrega/sdk-java/commit/a822d41b110e9fd61262283ec4654ad0a8afb7c5

These changes 'work' but are clearly not supported.

**Comment by georgantasp** [comment]
Same issue. Also going to point out that the sample code build is failing for this exact reason.

https://github.com/AuthorizeNet/sample-code-java/issues/64
https://travis-ci.org/AuthorizeNet/sample-code-java

**Comment by deepakgpt** [comment]
Getting below Error if I run the chargeCreditCard.java class with version anet-java-sdk-1.9.4.jar and HttpClient 4.5.3 and HttpCore 4.4.6 and JDK 1.7

_## Failed to get response
Error: javax.net.ssl.SSLException 
Received fatal alert: protocol_version_
 Please suggest me on this

**Comment by deepakgpt** [comment]
**According to this commit**  https://github.com/cdollar393/sdk-ava/commit/60984a99f30e2fc85a452ae22a29fa34d4e6e035

looks like you have fixed the HttpClient or Core version issue.
But If I go to source code  **https://github.com/cdollar393/sdk-java/blob/master/src/main/java/net/authorize/util/HttpCallTask.java** changed File

Not able to find that changes

Even in jar https://mvnrepository.com/artifact/net.authorize/anet-java-sdk/1.9.4 or 1.9.3 that changes is not there

So to fix that below Issue
Failed to get response
Error: javax.net.ssl.SSLException
Received fatal alert: protocol_version

I made the same changes **commit[https://github.com/cdollar393/sdk-ava/commit/60984a99f30e2fc85a452ae22a29fa34d4e6e035]** in the source code of anet-java-sdk

Then I generated the war on local with that changes and used it. It's starts working. But I think, this is not the best way to do this.

I want to know that why are those changes not in jar 1.9.3 or 1.9.4. Can you please make this changes in war

**Comment by Sapbasu15** [comment]
@deepakgpt Please specify the java 7 version and the environment it is running on.
Java Sample codes in the test runner seems to be running fine with open jdk 7. 
Also please try the below options :  
1. using -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2 (for the new httpClient version) parameters to set the environment
2. using System.setProperty("https.protocols", "TLSv1.2") in the code
3. Configuring Java settings to only use TLSv1.2 protocol 
We already have created a pull request to force HttpClient to use the TLSv1.2 only and it'll be added in the next SDK version.

**Comment by gnongsie** [comment]
Thank you for raising this issue. The fix for this has been merged and will be available in the release. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.

**Comment by AlbaCorvus** [comment]
using -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2 (for the new httpClient version) parameters to set the environment
> using System.setProperty("https.protocols", "TLSv1.2") in the code
> Configuring Java settings to only use TLSv1.2 protocol
Never use System.setProperty("","") bad practice as this will force any other third party API calls to use this version. I work with a very large web application with many packages many of which make external API calls. You should set the protocol against the client that makes the call.
For HttpClient you can set the SLLSocket and Registry to use a specific protocol version e.g

private Registry<ConnectionSocketFactory> getRegistry() {
        SSLContext sslContext;
        try {
            sslContext = SSLContexts.custom().build();
        SSLConnectionSocketFactory sslConnectionSocketFactory = new SSLConnectionSocketFactory(sslContext, new String[] { "TLSv1.2" },
                null, SSLConnectionSocketFactory.getDefaultHostnameVerifier());
        return RegistryBuilder.<ConnectionSocketFactory> create().register("http", PlainConnectionSocketFactory.getSocketFactory())
                .register("https", sslConnectionSocketFactory).build();
        } catch (KeyManagementException | NoSuchAlgorithmException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }
PoolingHttpClientConnectionManager clientConnectionManager = new PoolingHttpClientConnectionManager(getRegistry());
        HttpClient client = HttpClientBuilder.create().setConnectionManager(clientConnectionManager).build();
